2023-10-22 12:04 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Trading_Systeam.py", line 480, in main
    self.dataprovider_online.Binanceapp.execute_orders(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Data\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Data\custom.py", line 549, in execute_orders
    exchange_info_data['symbol'], order_quantity)
KeyError: 'symbol'

2023-10-22 12:20 ERROR Traceback (most recent call last):
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Trading_Systeam.py", line 480, in main
    self.dataprovider_online.Binanceapp.execute_orders(
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Data\custom.py", line 39, in warpper
    result = func(self, client, *args, **kwargs)
  File "C:\Users\user\Desktop\程式專區\TradingSysteam\Crypto_trading\Data\custom.py", line 557, in execute_orders
    for _ in range(order_times):
TypeError: 'float' object cannot be interpreted as an integer

